package com.jlgs.howmuchah.repository;

import com.jlgs.howmuchah.entity.InvitationLink;
import com.jlgs.howmuchah.enums.InvitationLinkStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

@Repository
public interface InvitationLinkRepository extends JpaRepository<InvitationLink, UUID> {

    // Find invitation link for verification
    Optional<InvitationLink> findByIdAndToken(UUID id, String token);

    // Counts number of links generated by a group within a certain time span
    long countByGroup_IdAndCreatedAtAfter(UUID groupId, LocalDateTime startDate);

    // Returns most recent ACTIVE link
    Optional<InvitationLink> findFirstByGroup_IdAndStatusOrderByCreatedAtDesc(
            UUID groupId,
            InvitationLinkStatus status
    );
}
